export const productDesign = [
    {
        id: 1,
        intern: `images/f2.jpg`,
        name: 'Precious Enarevba',
        medal: `images/gold.png`,
        bonus: "-",
        strike: "-",
        attendance: 100,
        appraisal: 4.6,
        task1: 8,
        task2: 9.5, 
        task3: 7,
        task4: 7,
        task5: 9,
        totalScore: 82.04,
    },
    {
        id: 2,
        intern: `images/p2.jpg`,
        name: 'Victory Erikume',
        medal: `images/silver.png`,
        bonus: "-",
        strike: "-",
        attendance: 95.5,
        appraisal: 3.9,
        task1: 9.5,
        task2: 7,
        task3: 8,
        task4: 5,
        task5: 9,
        totalScore: 79.51,
    },
    {   
        id: 3,
        intern: `images/p3.jpg`,
        name: 'Ikenna Okorie',
        medal: `images/bronze.png`,
        bonus: "2",
        strike: "-",
        attendance: 93.2,
        appraisal: 4,
        task1: 10,
        task2: 9,
        task3: 4,
        task4: 7,
        task5: 8,
        totalScore: 77.22,
    },
    {   
      id: 4,
      intern: `images/p4.jpg`,
      name: 'Chukwuka Eze',
      medal: ``,
      bonus: "-",
      strike: "-",
      attendance: 93.2,
      appraisal: 4.3,
      task1: 9,
      task2: 7.5,
      task3: 9,
      task4: 7,
      task5: 9,
      totalScore: 76.16,
  },
  {   
    id: 5,
    intern: `images/p5.jpg`,
    name: 'Uma Anidi',
    medal: ``,
    bonus: "1",
    strike: "-",
    attendance: 100,
    appraisal: 9,
    task1: 6.8,
    task2: 9,
    task3: 7,
    task4: 7.5,
    task5: 10,
    totalScore: 75.83,
  },
  {   
    id: 6,
    intern: `images/f7.jpg`,
    name: 'Islamiyat Badrudeen',
    medal: ``,
    bonus: "1",
    strike: "-",
    attendance: 100,
    appraisal: 9,
    task1: 6.8,
    task2: 9,
    task3: 7,
    task4: 7.5,
    task5: 10,
    totalScore: 75.83,
  },
];


  export const frontend = [
    {
        id: 1,
        intern: `images/p8.jpg`,
        name: 'Chinemerem Ojinta',
        medal: `images/gold.png`,
        bonus: 2,
        strike: "-",
        attendance: 100,
        appraisal: 4.2,
        task1: 9,
        task2: 10,
        task3: 9.8,
        task4: 9,
        task5: 10,
        totalScore: 90.29,
    },
    {
        id: 2,
        intern: `images/p2.jpg`,
        name: 'Victor Idam',
        medal: `images/silver.png`,
        bonus: 2,
        strike: "-",
        attendance: 100,
        appraisal: 4.9,
        task1: 10,
        task2: 10,
        task3: 7.5,
        task4: 9,
        task5: 9,
        totalScore: 84.85,
    },
    {   
        id: 3,
        intern: `images/p4.jpg`,
        name: 'Anyaegbunam Chigozirim',
        medal: `images/bronze.png`,
        bonus: 1,
        strike: "-",
        attendance: 97.1,
        appraisal: 4.4,
        task1: 10,
        task2: 9,
        task3: 9.2,
        task4: 8.5,
        task5: 7.5,
        totalScore: 84.89,
    },
    {   
        id: 4,
        intern: `images/f7.jpg`,
        name: 'Chidera Nnaji',
        medal: ``,
        bonus: 1,
        strike: "-",
        attendance: 82.4,
        appraisal: 4,
        task1: 9,
        task2: 10,
        task3: 9,
        task4: 8,
        task5: 9,
        totalScore: 82.5,
    },
    {   
      id: 5,
      intern: `images/p9.jpg`,
      name: 'Nuel Elekwachi',
      medal: ``,
      bonus: 1,
      strike: "-",
      attendance: 82.4,
      appraisal: 4,
      task1: 9,
      task2: 10,
      task3: 9,
      task4: 8,
      task5: 9,
      totalScore: 80.39,
  },
  {   
    id: 6,
    intern: `images/p3.jpg`,
    name: 'Ekene Akubue',
    medal: ``,
    bonus: "-",
    strike: "-",
    attendance: 82.4,
    appraisal: 4,
    task1: 9,
    task2: 10,
    task3: 9,
    task4: 8,
    task5: 9,
    totalScore: 79.92,
  },
  {   
    id: 7,
    intern: `images/p2.jpg`,
    name: 'Frederick Aniebonam',
    medal: ``,
    bonus: "-",
    strike: "-",
    attendance: 94.1,
    appraisal: 4,
    task1: 9,
    task2: 10,
    task3: 9,
    task4: 8,
    task5: 9,
    totalScore: 79.73,
  },
  {   
    id: 8,
    intern: `images/f5.jpg`,
    name: 'Somtochukwu Ozonnadi',
    medal: ``,
    bonus: "-",
    strike: "-",
    attendance: 94.1,
    appraisal: 4,
    task1: 9,
    task2: 10,
    task3: 9,
    task4: 8,
    task5: 9,
    totalScore: 79.71,
  },
  {   
    id: 9,
    intern: `images/f7.jpg`,
    name: 'NZEH FAVOUR',
    medal: ``,
    bonus: "-",
    strike: "-",
    attendance: 94.1,
    appraisal: 4,
    task1: 9,
    task2: 10,
    task3: 9,
    task4: 8,
    task5: 9,
    totalScore: 79.71,
  },
  {   
    id: 10,
    intern: `images/f7.jpg`,
    name: 'NZEH FAVOUR',
    medal: ``,
    bonus: "-",
    strike: "-",
    attendance: 94.1,
    appraisal: 4,
    task1: 9,
    task2: 10,
    task3: 9,
    task4: 8,
    task5: 9,
    totalScore: 79.71,
  },
];

  export const backend = [
    {
        id: 1,
        intern: `images/p7.jpg`,
        name: 'Okechukwu Ani',
        medal: `images/gold.png`,
        bonus: 2,
        strike: "-",
        attendance: 100,
        appraisal: 4.5,
        task1: 8,
        task2: 9.5,
        task3: 7,
        task4: 7,
        task5: 9,
        totalScore: 82.04,
    },
    {
        id: 2,
        intern: `images/p8.jpg`,
        name: 'Benjamine Ovu',
        medal: `images/silver.png`,
        totalScore: 79.51,
    },
    {   
        id: 3,
        intern: `images/p9.jpg`,
        name: 'Uche Obi',
        medal: `images/bronze.png`,
        totalScore: 77.22,
    },
  ];

  export const web3 = [
    {
        id: 1,
        intern: `images/p7.jpg`,
        name: 'Jide Adegoke',
        medal: `images/gold.png`,
        bonus: 2,
        strike: "-",
        attendance: 100,
        appraisal: 4.5,
        task1: 8,
        task2: 9.5,
        task3: 7,
        task4: 7,
        task5: 9,
        totalScore: 82.04,
    },
    {
        id: 2,
        intern: `images/p8.jpg`,
        name: 'Chioma Okoye',
        medal: `images/silver.png`,
        totalScore: 79.51,
    },
    {   
        id: 3,
        intern: `images/p9.jpg`,
        name: 'Ebere Aganama',
        medal: `images/bronze.png`,
        totalScore: 77.22,
    },
    {   
        id: 4,
        intern: `images/p9.jpg`,
        name: 'Ebere Aganama',
        medal: `images/bronze.png`,
        totalScore: 77.22,
    },   
  ];

  export const Tracks = [
    {
        id: 1,
        Track: 'Product Design',
        Interns: 10,
    },
    {
        id: 2,
        Track: 'Frontend',
        Interns: 20,
    },
    {
        id: 3,
        Track: 'Backend',
        Interns: 15,
    },
    {
        id: 4,
        Track: 'Web3',
        Interns: 5,
    },
  ]

export const data = [
    {
      name: 'Product Design',
      uv: 40,
      pv: 2400,
      amt: 2400,
    },
    {
      name: 'Frontend',
      uv: 30,
      pv: 1398,
      amt: 2210,
    },
    {
      name: 'Backend',
      uv: 45,
      pv: 9800,
      amt: 2290,
    },
    {
      name: 'Web3',
      uv: 27,
      pv: 3908,
      amt: 2000,
    },    
  ];




